language: node_js
node_js:
  - "stable"
env:
  - API_BASE='/api/v1/' DEBUG='debug' ENDPOINT='localhost' DB_NAME='travis_ci_test' PORT='5432' DB_USER='postgres' PASSWORD='password'
services:
  - postgresql
addons:
  postgresql: 10
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'password';" -U postgres
install:
  - npm i
script:
  - npm run lint
  - npm run ts-test
  - npm run dev && npm test
