language: node_js
node_js:
  - "stable"
env:
  - API_BASE='/api/v1/' DEBUG='debug' ENDPOINT='localhost' DB_NAME='metrics_db' PORT='5432' DB_USER='admin' PASSWORD='password'
services:
  - postgresql
before_script:
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - psql -f schema.sql
install:
  - npm i
script:
  - npm run lint
  - npm run dev
  - npm run test
